{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rancher-centralized-monitoring.fullname" . }}
  labels:
    {{- include "rancher-centralized-monitoring.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.observability.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rancher-centralized-monitoring.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.observability.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}