apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-centralized-monitoring.fullname" . }}
  labels:
    {{- include "rancher-centralized-monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "rancher-centralized-monitoring.selectorLabels" . | nindent 4 }}